name: 'Install Kops'
description: 'Setup Kops/Kubectl'
author: 'Cameron Larsen @cam3ron2'
branding:
  icon: 'terminal'
  color: 'blue'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/install.sh
      shell: bash