name: "Manifest Validation"
description: "Validates kube manifests and ensures they are buildable by kustomize"
author: "Cameron Larsen @cam3ron2"
branding:
  icon: "terminal"
  color: "blue"

inputs:
  base:
    description: "relative path to base directory"
    required: true
  overlay:
    description: "relative path to overlay directory"
    required: true

runs:
  using: "composite"
  steps:
    - uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kubectl: "1.21.5"
          kustomize: "4.5.2"
          kubeval: "0.16.1"
          conftest: "0.30.0"
    - run: ${{ github.action_path }}/validate_manifests.sh ${{ inputs.base }}
      shell: bash
      id: validate_manifests_base
    - run: ${{ github.action_path }}/validate_kustomize.sh ${{ inputs.base }}
      shell: bash
      id: validate_kustomize_base
    - run: ${{ github.action_path }}/validate_manifests.sh ${{ inputs.overlay }}
      shell: bash
      id: validate_manifests_overlay
    - run: ${{ github.action_path }}/validate_kustomize.sh ${{ inputs.overlay }}
      shell: bash
      id: validate_kustomize_overlay
