name: "EKS managed NodeGroup AMI Updater"
description: "Updates the AMI used by managed EKS NodeGroups"
author: "Cameron Larsen @cam3ron2"
branding:
  icon: "terminal"
  color: "blue"

inputs:
  cluster_name:
    description: "name of the cluster we will be updating"
    required: true
  region:
    description: "Region of k8s resources"
    required: true

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/run.sh ${{ inputs.cluster_name }} ${{ inputs.region }}
      working-directory: ${{ github.action_path }}
      shell: bash
