name: "K8s App Updater"
description: "Runs update.sh scripts in k8s-apps or sre-apps to update each app and open a PR"
author: "Cameron Larsen @cam3ron2"
branding:
  icon: "terminal"
  color: "blue"

inputs:
  app:
    description: "The app to update"
    required: true
  repo:
    description: "The repo to update"
    required: true
  path: 
    description: "The path to the app"
    required: true
  script:
    description: "The script to run"
    required: false
    default: "update.sh"
  branch: 
    description: "The branch to update"
    required: false
    default: "main"

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/setup.sh
      working-directory: ${{ github.action_path }}
      shell: bash

    - name: update
      id: update
      env:
        APP_PATH: ${{ inputs.path }}
        SCRIPT: ${{ inputs.script }}
      run: |
        cd ${APP_PATH} && ./${SCRIPT} && cd ..
      shell: bash

    - name: pull request
      env:
        APP: ${{ inputs.app }}
        REPO: ${{ inputs.repo }}
        APP_PATH: ${{ inputs.path }}
      run: |
        git config --global user.email "ops@kuali.co"
        git config --global user.name "Kuali Ops (github-actions)"
        ts=$(date +%Y-%m-%d)
        echo "BRANCHES:"
        git branch -r
        git checkout ${{ inputs.branch }}
        git checkout -b "update-base-${ts}"
        git add ${APP_PATH} -A
        changes=$(git status -s)
        if [ -n "${changes}" ]; then 
          echo "Changes detected, committing..."
          git commit -m "Update base ${ts}"
          git push --set-upstream origin "update-base-${ts}"
          PR=$(hub pull-request -p -b ${{ inputs.branch }} -m "${APP} Update: ${ts}" | grep github.com) 
          [[ "${PR}" =~ "${REPO}/pull/" ]] || { git checkout ${{ inputs.branch }}; git push origin --delete "update-base-${ts}"; git checkout -d "update-base-${ts}"; exit 1; }
          echo "::set-output name=pr::${PR}"
          echo "::set-output name=changes::true"
        else
          echo "No changes detected, skipping commit..."
          echo "::set-output name=changes::false"
        fi
      shell: bash
