name: "K8s App Updater"
description: "Runs update.sh scripts in k8s-apps or sre-apps to update each app and open a PR"
author: "Cameron Larsen @cam3ron2"
branding:
  icon: "terminal"
  color: "blue"

inputs:
  app:
    description: "The app to update"
    required: true

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/setup.sh
      working-directory: ${{ github.action_path }}
      shell: bash
    - run: ${{ github.action_path }}/run.sh ${{ inputs.app }}
      working-directory: ${{ github.action_path }}
      shell: bash
