name: 'Deploy Env'
description: 'Deploys new environment variables to aptible'
inputs:
  app_name:
    description: 'Name of the app in aptible'
    required: true
  yaml_name:
    description: 'Name of the yaml file where env lives'
    required: false
  aptible_username:
    description: 'Username of aptible account'
    required: true
  aptible_password:
    description: 'Password of aptible account'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
