name: Docker Publish
description: Publishes a docker image
branding:
  icon: box
  color: blue
inputs:
  docker_password:
    description: Docker password
    required: false
    default: ${{ github.token }}
  docker_username:
    description: Docker username (defaults to GITHUB_ACTOR, which works for docker.pkg.github.com)
    required: false
    default: ${{ github.actor }}
  docker_image_name:
    description: Docker Image Name (defaults to repo name)
    required: false
  docker_registry:
    description: Docker registry
    required: false
    default: docker.pkg.github.com
  docker_context_path:
    description: Docker Context Path relative to the root of the project
    required: false
    default: '.'
  dockerfile:
    description: The path to the dockerfile relative to the root of the project
    required: false
    default: Dockerfile
  build_params:
    description: Build params to send to docker build
    required: false
    default: ''
runs:
  using: docker
  image: Dockerfile
